# note: behavior depends on installed packages with class-specific methods
# class 'prcomp'
iris_pca <- prcomp(iris[, -5L], scale = TRUE)
iris_pca_ord <- as_tbl_ord(iris_pca)
plot(iris_pca)
plot(iris_pca_ord)
screeplot(iris_pca)
screeplot(iris_pca_ord)
biplot(iris_pca)
biplot(iris_pca_ord)
# class 'ca'
smoke_ca <- ca::ca(ca::smoke)
smoke_ca_ord <- as_tbl_ord(smoke_ca)
plot(smoke_ca)
plot(smoke_ca_ord)
#screeplot(smoke_ca)
screeplot(smoke_ca_ord)
#biplot(smoke_ca)
biplot(smoke_ca_ord, var.axes = FALSE)
# class 'lra'
arrests_lra <- lra(subset(USArrests, select = -UrbanPop))
arrests_lra_ord <- as_tbl_ord(arrests_lra)
#plot(arrests_lra)
plot(arrests_lra_ord)
#screeplot(arrests_lra)
screeplot(arrests_lra_ord)
#biplot(arrests_lra)
biplot(arrests_lra_ord, var.axes = FALSE)
