# ------------------------------------------------------------------------------
# Generated by 'build/build.r': do not edit by hand.
# ------------------------------------------------------------------------------

#' @title Convenience geoms for row and column matrix factors
#' 
#' @description These geometric element layers (geoms) pair
#'   conventional **ggplot2** geoms with [stat_rows()] or
#'   [stat_cols()] in order to render elements for one or the other
#'   matrix factor of a tbl_ord. They understand the same aesthetics
#'   as their corresponding conventional geoms.
#' 
#' @name biplot-geoms
#' @family biplot layers
#' @import ggplot2
#' @importFrom ggrepel
#'   GeomTextRepel
#'   GeomLabelRepel
#'   geom_text_repel
#'   geom_label_repel
#' @inheritParams ggplot2::layer
#' @template param-matrix
#' @template param-geom
#' @inheritParams ggplot2::geom_point
#' @inheritParams ggplot2::geom_path
#' @inheritParams ggplot2::geom_polygon
#' @inheritParams ggplot2::geom_text
#' @inheritParams ggplot2::geom_label
#' @inheritParams ggrepel::geom_text_repel
#' @inheritParams ggrepel::geom_label_repel
#' @inheritParams geom_axis
#' @inheritParams geom_dims_axis
#' @inheritParams geom_lineranges
#' @inheritParams geom_pointranges
#' @inheritParams geom_dims_lineranges
#' @inheritParams geom_dims_pointranges
#' @inheritParams geom_isoline
#' @inheritParams geom_dims_isoline
#' @inheritParams geom_dims_path
#' @inheritParams geom_dims_point
#' @inheritParams geom_dims_polygon
#' @inheritParams geom_text_radiate
#' @inheritParams geom_dims_text_radiate
#' @inheritParams geom_dims_text
#' @inheritParams geom_dims_label
#' @inheritParams geom_dims_text_repel
#' @inheritParams geom_dims_label_repel
#' @inheritParams geom_vector
#' @inheritParams geom_dims_vector
NULL

#' @export
ggrepel::geom_text_repel
#' @export
ggrepel::geom_label_repel
